apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open5gran
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: open5gran
    server: ''
  source:
    path: 5gran
    repoURL: 'https://github.com/adetalhouet/cnvopen5gcore'
    targetRevision: HEAD
    helm:
      releaseName: open5g-ran
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

