---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
-  target:
     kind: ConfigMap
     name: skupper-site
   patch: |-
    - op: replace
      path: /data/name
      value: remote
